version: "3.8"

services:
  event-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    ports:
      - 8080:8080
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - CORS_ORIGIN_HOST=${CORS_ORIGIN_HOST}
      - CORS_ORIGIN_PORT=${CORS_ORIGIN_PORT}
    stdin_open: true
    tty: true
